server:
  port: 8081
  servlet:
    context-path: /v1.0/
spring:
  application:
    name: app-barber-shop-appointment-app-api
    version: develop
  sleuth:
     sampler:
        probability: 1
  datasource:
    url: url
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
---
server:
  port: ${PORT}
  servlet:
    context-path: /v1.0/
spring:
  profiles: release
  application:
    name: app-barber-shop-appointment-app-api
    version: ${APP_VERSION}
  sleuth:
     sampler:
        probability: 1
  datasource:
    url: ${SQL_URL_CONECTION}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 60000
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
